version: '3.8'

services:
  rds:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
      - "8081:81"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - rds-volume:/data
    restart: always
  web:
    container_name: hwan-server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/hwan
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - redis
  redis:
    image: redis:6.0
    container_name: hwan-redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"

volumes:
  rds-volume:
    driver: local
  redis-volume:
    driver: local