# 글로벌 설정

# external
external:
  client:
    kakao:
      profile:
        base-url: https://kapi.kakao.com
        url: /v2/user/me
    google:
      profile:
        base-url: https://www.googleapis.com
        url: /oauth2/v2/userinfo
    naver:
      profile:
        base-url: https://openapi.naver.com
        url: /v1/nid/me

# 로그설정
logging:
  level:
    sql: debug
    org.hibernate.type: trace

# 스프링 mvc, session, batch
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
  batch:
    jdbc:
      initialize-schema: always

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: bWmyogM0PGu9x6jxz8eX
            client-secret: ${{secrets.NAVER_CLIENT_SECRET}}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          google:
            client-id: 143667160680-56cpb80as4f6onvs0mkc9slm2v516n6f.apps.googleusercontent.com
            client-secret: ${{secrets.GOOGLE_CLIENT_SECRET}}
            scope:
              - email
              - profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
---
# 프로필 local
spring:
  config:
    activate:
      on-profile: local

# 데이터 베이스
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/security
    username: cos
    password: cos1234

# 포트설정 및 인코딩
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
          show_sql: true
---
# 프로필 dev
spring:
  config:
    activate:
      on-profile: dev