# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_NAME: hwan_community_project
  BUCKET_NAME: hwan-community-code
  CODE_DEPLOY_APP_NAME: Hwan-Community
  DEPLOYMENT_GROUP_NAME: HwanCommunity_deploy

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # addition executable permission
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # clean build with gradle without test
    - name: Build with Gradle
      run : ./gradlew clean build --exclude-task test

    # make a zip file
    - name: Make a zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
